export const CONTESTANT_ID = 1;
export const VOTER_ID = 2;
export const REDIRECT_TO_EVENT_KEY = 'redirect_to_event';

export const NOTIFICATION_TYPE = {
  NOTIF_PAYMENT_VIDEO_PENDING: 1,
  NOTIF_PAYMENT_VIDEO_SUCCESS: 2,
  NOTIF_PAYMENT_MEMBERSHIP_PENDING: 3,
  NOTIF_PAYMENT_MEMBERSHIP_SUCCESS: 4,
  NOTIF_ACTIVE_MEMBERSHIP: 5
};
